apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-app-override
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/leehaeman/test-argocd
    targetRevision: HEAD
    path: dev/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
