apiVersion: v2
name: nginx-ingress-app-override
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: 4.1.2
    repository: https://github.com/kubernetes/ingress-nginx
